"""create like buttion

Revision ID: 6dd4d6a6ba2e
Revises: e0c8d3c670f6
Create Date: 2026-06-08 17:53:48.406003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd4d6a6ba2e'
down_revision: Union[str, Sequence[str], None] = 'e0c8d3c670f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
