"""created relationships between generated_blog and blogimage

Revision ID: 8398d6a1eab6
Revises: cb919eaab72e
Create Date: 2026-05-23 11:36:54.177916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8398d6a1eab6'
down_revision: Union[str, Sequence[str], None] = 'cb919eaab72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_images_blog_id_fkey'), 'blog_images', type_='foreignkey')
    op.create_foreign_key(None, 'blog_images', 'generated_blogs', ['blog_id'], ['blog_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_images', type_='foreignkey')
    op.create_foreign_key(op.f('blog_images_blog_id_fkey'), 'blog_images', 'generated_blogs', ['blog_id'], ['blog_id'])
    # ### end Alembic commands ###
