"""create like buttion

Revision ID: 9a46c89c2451
Revises: 0a4beaa0ae03
Create Date: 2026-06-08 11:23:54.789357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a46c89c2451'
down_revision: Union[str, Sequence[str], None] = '0a4beaa0ae03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('generated_blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_blogs_blog_id'), 'generated_blogs', ['blog_id'], unique=True)
    op.create_index(op.f('ix_generated_blogs_id'), 'generated_blogs', ['id'], unique=False)
    op.create_index(op.f('ix_generated_blogs_user_id'), 'generated_blogs', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('blog_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['generated_blogs.blog_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_images_blog_id'), 'blog_images', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_images_filename'), 'blog_images', ['filename'], unique=True)
    op.create_index(op.f('ix_blog_images_id'), 'blog_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_images_id'), table_name='blog_images')
    op.drop_index(op.f('ix_blog_images_filename'), table_name='blog_images')
    op.drop_index(op.f('ix_blog_images_blog_id'), table_name='blog_images')
    op.drop_table('blog_images')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_generated_blogs_user_id'), table_name='generated_blogs')
    op.drop_index(op.f('ix_generated_blogs_id'), table_name='generated_blogs')
    op.drop_index(op.f('ix_generated_blogs_blog_id'), table_name='generated_blogs')
    op.drop_table('generated_blogs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
