name: CI-CD

on: push
    


jobs:

  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MIGRATION_DATABASE_URL: ${{ secrets.MIGRATION_DATABASE_URL }}
      SECRET_KEY: test-secret-key
      S3_BUCKET_NAME: test-bucket
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Unit Tests
        run: uv run pytest
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
    steps:
      - name: Deploy
        run: echo "Deploying..."

      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.PROJECT_ID }}
          

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build  Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}:${{ github.sha }} \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated \
          --memory=2Gi \
          --cpu=2 \
          --min-instances=0 \
          --max-instances=10 \
          --concurrency=10 \
          --update-secrets=/secrets/app/.env=app-config-prod:latest
          
  

      
     
